CREATE SCHEMA EOH;

CREATE TABLE EOH.INVOICE (
	ID                   numeric(19,0) GENERATED ALWAYS AS IDENTITY  NOT NULL,
	CLIENT               varchar(255)   NOT NULL,
	VAT_RATE             numeric(19,0)   NOT NULL,
	INVOICE_DATE         date  DEFAULT CURRENT_DATE NOT NULL,
	CONSTRAINT PK_INVOICE_ID PRIMARY KEY ( ID )
 );

CREATE TABLE EOH.LINE_ITEMS (
	ID                   numeric(19,0) GENERATED ALWAYS AS IDENTITY  NOT NULL,
	QUANTITY             numeric(19,0)   NOT NULL,
	DESCRIPTION          varchar(255)   NOT NULL,
	UNIT_PRICE           double   ,
	FK_INVOICE_ID        numeric(19,0)   NOT NULL,
	CONSTRAINT PK_LINE_ITEMS_ID PRIMARY KEY ( ID )
 );

ALTER TABLE EOH.LINE_ITEMS ADD CONSTRAINT FK_LINE_ITEMS_INVOICE FOREIGN KEY ( FK_INVOICE_ID ) REFERENCES EOH.INVOICE( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

INSERT INTO EOH.INVOICE(CLIENT, VAT_RATE) VALUES ('ABC Giant Corp', 15);
INSERT INTO EOH.LINE_ITEMS(QUANTITY, DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID) VALUES (35, 'Bic click black pens', 12.00, (SELECT ID FROM EOH.INVOICE WHERE CLIENT = 'ABC Giant Corp'));
INSERT INTO EOH.LINE_ITEMS(QUANTITY, DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID) VALUES (14, 'Parker black pens', 142.00,  (SELECT ID FROM EOH.INVOICE WHERE CLIENT = 'ABC Giant Corp'));

INSERT INTO EOH.INVOICE(CLIENT, VAT_RATE) VALUES ('QWERTY Giant Corp', 15);
INSERT INTO EOH.LINE_ITEMS(QUANTITY, DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID) VALUES (12, 'Dell keyboard', 350.00, (SELECT ID FROM EOH.INVOICE WHERE CLIENT = 'QWERTY Giant Corp'));
INSERT INTO EOH.LINE_ITEMS(QUANTITY, DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID) VALUES (12, 'Dell wireless mouse', 150.00, (SELECT ID FROM EOH.INVOICE WHERE CLIENT = 'QWERTY Giant Corp'));

